language: node_js
node_js:
- '7'
install:
- npm install
script:
- npm run build
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip_cleanup: true
  local_dir: build
  fqdn: budget.sebastienbarbier.com
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master