language: node_js
node_js:
  - "8.9.4"
install:
  - source scripts/4660933598635778-openrc.sh
  - pip install python-swiftclient python-keystoneclient --user
  - npm install
script:
  - npm run build
deploy:
  # deploy next to the staging environment
  - provider: script
    script: bash scripts/deploy.sh
    on:
      branch: master
