language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: j1/RLZNQM4AAGqpMIsv1AVBlTfl7PvOqUhnHvAV7YR3otAAUbhZ5uVMH3mxKneei3DOheJF7RAS3el/lczUx12637QzTgYbxsoUcgLcR4lVr0ruu43XqodjT6TZf+yO6QukGHNsVgBIO1SvqDj3pDnmJW297yDcR6s1FWGEoXDfQMShXG9wfWBwAkJwl8+rkhwYSVpyUfHfE5pQLd/INgMEpJI3uSFn0T+p0ZY+YXAE25EJifxPjqIo7+LhsHsNqARz7YPw1TIJS9pIYhqkUjtBuNPj6Xm6zhzC+6tpcjy1vggx5PBtV55FyTKd1nE0iUxX2AqQ08kStbpRTUly3VaTk8VjRqm40zYq3qlxyENkcJewfKdzSdF7x6ea6afEz6624YEIcKFXxSU1D5lERDfEsLxkKCMBzkhwdl5vqj7BM+iMSa3+76CluruAiHZZR+KClfVeIXLglvIQm0VOiRyTxiu5kYvyp7c7Xvkt/DJbJmC+Ln1GsScEY7TOpQem9P16N+XCTw+7E2nHPtAYTJ5jQLMhIC5PQ1c6t0anGuCkAnj8UUa5RdU9qG7WrTLCbckhhX/H9oQMNNlT9dkdbcQL707yFqppHibejP78FSPrrsVUArT9C2DSCg7HkIRBWxq/ovDGR98tdS95YKbDmHg3coy6U9UGrGc7rl2ATDAQ=
  app: app-723e-react
  on:
      branch: master