language: node_js
node_js:
- '7'
install:
- npm install
script:
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  fqdn: budget.sebastienbarbier.com
  keep-history: true
  verbose: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master